// Login
export const SET_LOGGED_IN = 'SET_LOGGED_IN'
export const SET_USER_NAME = 'SET_USER_NAME'
export const SET_USER_MAIL = 'SET_USER_MAIL'
export const SET_NAVBAR_MENU_OPEN = 'SET_NAVBAR_MENU_OPEN'
export const SET_NAVBAR_MENU_ANCHOR_EL = 'SET_NAVBAR_MENU_ANCHOR_EL'

// Main Wrapper
export const SET_DRAWER_OPEN = 'SET_DRAWER_OPEN'