// Profile
export const SET_LOGGED_IN = 'SET_LOGGED_IN'
export const PROFILE_LOGIN = 'PROFILE_LOGIN'
export const PROFILE_LOGOUT = 'PROFILE_LOGOUT'
export const PROFILE_SET_USER_VNAME = 'PROFILE_SET_USER_VNAME'
export const PROFILE_SET_USER_NNAME = 'PROFILE_SET_USER_NNAME'
export const PROFILE_SET_USER_MAIL = 'PROFILE_SET_USER_MAIL'
export const PROFILE_SET = 'PROFILE_SET'

// Main Wrapper
export const MAIN_WRAPPER_SET_DRAWER_OPEN = 'MAIN_WRAPPER_SET_DRAWER_OPEN'

// Profile Button???
export const SET_NAVBAR_MENU_OPEN = 'SET_NAVBAR_MENU_OPEN'
export const SET_NAVBAR_MENU_ANCHOR_EL = 'SET_NAVBAR_MENU_ANCHOR_EL'

// Login Popup
export const LOGIN_POPUP_SET_NAME = 'LOGIN_POPUP_SET_NAME'
export const LOGIN_POPUP_SET_PW = 'LOGIN_POPUP_SET_PW'
export const LOGIN_POPUP_SET_OPEN = 'LOGIN_POPUP_SET_OPEN'
export const LOGIN_POPUP_SET_ERROR = 'LOGIN_POPUP_SET_ERROR'
export const LOGIN_POPUP_SET_ERROR_MSG = 'LOGIN_POPUP_SET_ERROR_MSG'

// Autobahn
export const AUTOBAHN_SET_CONNECTION_STATE = 'AUTOBAHN_SET_CONNECTION_STATE'
export const AUTOBAHN_CONNECTION_STATES = {
    connected: 'connected',
    disconnected: 'disconnected',
    connecting: 'connecting',
}

// UserMessage
export const USERMESSAGE_SET_MESSAGE = 'USERMESSAGE_SET_MESSAGE'
export const USERMESSAGE_SET_OPEN = 'USERMESSAGE_SET_OPEN'
export const USERMESSAGE_SET_CLOSE_DURATION = 'USERMESSAGE_SET_CLOSE_DURATION'
